local Players = game:GetService("Players")
local ServerScriptService = game:GetService("ServerScriptService")
local ProfileStore = require(ServerScriptService.ServerPackages.ProfileStore)
local DataStore = require(script.Parent.DataStore)
local p = require(script.Parent.p)
local store = DataStore.New("PlayerData", { Coins = 0 })
DataStore.Settings.Logging.All = true
--[[Players.PlayerAdded:Connect(function(player)
	local pr = store:StartSessionAsync(player)
	pr:Save("Low")
	print(store:HasSession(player))
	task.wait(2)
	print(DataStore.EndPlayerSessions(player))
end)
Players.PlayerRemoving:Connect(function(player)
	--DataStore.Stores["PlayerData"][player.UserId]
	print(store:GetSession(player):EndSession())
end)
--]]
DataStore.Start({ { Store = store } })
