[package]
name = "vivuyr/datastore"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

license = "MIT"
authors = ["vivuyr"]

description = "DataStore is a typed Roblox Luau wrapper around ProfileStore."

repository = "https://github.com/vivuyr/DataStore"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"
